### ISSUE TITLE
"ESLint configuration in plugin:gjs/extension is invalid"

### ISSUE THREAD

**Issue by MichaelInfoworks** [rockon999/eslint-plugin-gjs#3]
Hey there, I'm getting an issue trying to use this extension.  Followed the README.
```
$ DEBUG=eslint:* eslint .
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +0ms
  eslint:ignored-paths Looking for ignore file in /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org +0ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cli-engine Processing /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/extension.js +0ms
  eslint:cli-engine Linting /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/extension.js +0ms
  eslint:config Constructing config file hierarchy for /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/.eslintrc +1ms
  eslint:config-file Loading config file: /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/.eslintrc +0ms
  eslint:plugins Loaded plugin gjs (eslint-plugin-gjs@1.0.4) (from /home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint-plugin-gjs/lib/index.js) +0ms
  eslint:config-file Loading plugin:gjs/extension +134ms
  eslint:config-file Attempting to resolve eslint-plugin-gjs +0ms
  eslint:config-file Loading JS config file: /home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint-plugin-gjs/lib/index.js +0ms
ESLint configuration in plugin:gjs/extension is invalid:
	- Unexpected top-level property "plugin".

Referenced from: /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/.eslintrc
Error: ESLint configuration in plugin:gjs/extension is invalid:
	- Unexpected top-level property "plugin".

Referenced from: /home/michael/.local/share/gnome-shell/extensions/gnomodoro@iBelieveInHumanDignity.org/.eslintrc
    at validateConfigSchema (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-validator.js:221:15)
    at Object.validate (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-validator.js:238:5)
    at loadFromDisk (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:516:19)
    at load (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:559:20)
    at configExtends.reduceRight (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:403:26)
    at loadFromDisk (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:523:22)
    at Object.load (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/home/michael/.nvm/versions/node/v8.10.0/lib/node_modules/eslint/lib/config.js:227:44)
```

**Comment by jtojnar** [comment]
This was fixed in #1
